from nltk.corpus import stopwords
from sklearn import set_config
import nltk

import logging
logging.basicConfig(level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)



# set output as pandas on sklearn
set_config(transform_output="pandas")

# download various dataset
# if it's already downloaded, it's instantaneously retrieve from a local cache
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger')

# generic stop words used in preprocessing
STOP_WORDS = set(stopwords.words('english'))

# additionnal custom stop words used in preprocessing for recipe
RECIPE_STOPWORDS = ['minute', 'le',
                    'ingredient','preparation','dish','add',
                    'course','top','hour','combine',
                    'cup','pour','recipe','serving',
                    'taste','together','one','set',
                    'remaining','occasion','something','inch',
                    'let','time','half','degree',
                    "f",'cuisine','bring','use',
                    'food','cooking','put','aside',
                    'lightly','equipment','piece','spoon',
                    'using','cooked','tablespoon','turn',
                    '°f', '°c', '½re','½s'
                     ]
# additionnal custom stop words used in preprocessing for tags
TAGS_STOPWORDS = ['60-minutes-or-less','30-minutes-or-less',
                  '15-minutes-or-less','time-to-make',
                  'preparation', 'course', 'main-ingredient',
                  'cuisine', '4-hours-or-less', '3-steps-or-less',
                  '5-ingredients-or-less','','baja',
                  'Throw the ultimate fiesta with this sopaipillas recipe from Food.com.',
                  'less_thansql:name_topics_of_recipegreater_than','main ingredient'
                  ]
# replacement of tags to correct typo and similar tags
TAGS_REPLACEMENTS = {'eggs breakfast':'breakfast eggs',
                    'for large groups holiday event':'for large groups',
                    'healthy 2':'healthy',
                    'heirloom historical recipes':'heirloom historical',
                    'irish st patricks day':'st patricks day',
                    'lasagne':'lasagna',
                    'pasta rice and grains elbow macaroni':'pasta rice and grains',
                    'pork loins':'pork loin',
                    'pork loins roast':'pork loin',
                    'rosh hashana':'rosh hashanah',
                    'simply potatoes2':'simply potatoes',
                    'steaks':'steak',
                    'super bowl':'superbowl',
                    'for-large-groups':'test'
                    }
# list of columns on which text preprocessing will be applied
RECIPE_COLUMNS_FOR_TEXT_PREPROC = [
        'name',
        'description',
        'merged_steps',
        'merged_ingredients'
    ]

# list of columns on which numeric preprocessing will be applied
RECIPE_COLUMNS_FOR_NUMERIC_PREPROC = [
        'minutes',
        'calories',
        'total_fat_pdv',
        'sugar_pdv',
        'sodium_pdv',
        'protein_pdv',
        'saturated_fat_pdv',
        'carbohydrates_pdv']

# setting to normalise the number of minutes per recipe
# any recipe with 'minutes' lower than this value will be set to MINUTES_CLIP_LOWER
MINUTES_CLIP_LOWER=5
# any recipe with 'minutes' greater than this value will be set to MINUTES_CLIP_UPPER
MINUTES_CLIP_UPPER=130

# setting to normalise the number of steps per recipe
# any recipe with 'steps' lower than this value will be set to N_STEPS_CLIP_LOWER
N_STEPS_CLIP_LOWER=0
# any recipe with 'steps' higher than this value will be set to N_STEPS_CLIP_UPPER
N_STEPS_CLIP_UPPER=40

# parameters to train W2V model
W2V_VECTOR_SIZE = 100
W2V_WINDOW = 5
W2V_MIN_COUNT = 1

# number of similar recipe to return
# the actual number of recipe return is KNN_N_NEIGHBORS - 1
KNN_N_NEIGHBORS = 6 # should not be inferior to 2. 1 would return itself

# ingredients preprocessing : replace some ingredient by simpler values
REPLACE_INGREDIENT = {'acorn squash':'acorn squash',
    'active dry yeast':'active dry yeast',
    'adobo seasoning':'adobo sauce',
    'adobo sauce':'adobo sauce',
    'agave nectar':'agave nectar',
    'alfredo sauce':'alfredo sauce',
    'allbran cereal':'allbran cereal',
    'allpurpose flour':'allpurpose flour',
    'unbleached allpurpose flour':'allpurpose flour',
    'whole allspice':'allspice',
    'allspice berry':'allspice',
    'allspice':'allspice',
    'ground allspice':'allspice',
    'toasted almond':'almond',
    'whole almond':'almond',
    'almond':'almond',
    'slivered almond':'almond',
    'sliced almond':'almond',
    'almond meal':'almond',
    'blanched almond':'almond',
    'ground almond':'almond',
    'almond extract':'almond extract',
    'almond flour':'almond flour',
    'almond milk':'almond milk',
    'almond paste':'almond paste',
    'aluminum foil':'aluminum foil',
    'amaretto':'amaretto',
    'american cheese':'american cheese',
    'dried ancho chile powder':'ancho chili',
    'anchovy paste':'anchovy',
    'anchovy':'anchovy',
    'anchovy fillet':'anchovy',
    'andouille sausage':'andouille sausage',
    'angel food cake':'angel food cake',
    'angel hair pasta':'angel hair pasta',
    'anise seed':'anise',
    'red apple':'apple',
    'golden delicious apple':'apple',
    'green apple':'apple',
    'apple butter':'apple',
    'apple':'apple',
    'granny smith apple':'apple',
    'cooking apple':'apple',
    'apple cider':'apple cider',
    'cider vinegar':'apple cider vinegar',
    'apple cider vinegar':'apple cider vinegar',
    'apple juice':'apple juice',
    'applesauce':'applesauce',
    'unsweetened applesauce':'applesauce',
    'apricot':'apricot',
    'apricot jam':'preserve',
    'apricot nectar':'apricot nectar',
    'arborio rice':'arborio rice',
    'arrowroot':'arrowroot',
    'artichoke':'artichoke heart',
    'artichoke heart':'artichoke heart',
    'marinated artichoke heart':'artichoke heart',
    'arugula':'arugula',
    'asiago cheese':'asiago cheese',
    'asparagus':'asparagus',
    'asparagus spear':'asparagus',
    'fresh asparagus':'asparagus',
    'avocado':'avocado',
    'bacon grease':'bacon',
    'lean bacon':'bacon',
    'bacon':'bacon',
    'canadian bacon':'bacon',
    'cooked bacon':'bacon',
    'bacon bit':'bacon',
    'bacon dripping':'bacon dripping',
    'baguette':'baguette',
    'french baguette':'baguette',
    'baked bean':'baked bean',
    'baking cocoa':'baking cocoa',
    'baking mix':'baking mix',
    'baking potato':'potato',
    'baking powder':'baking powder',
    'baking soda':'baking soda',
    'bicarbonate of soda':'baking soda',
    'white balsamic vinegar':'balsamic vinegar',
    'balsamic vinegar':'balsamic vinegar',
    'bamboo shoot':'bamboo shoot',
    'banana':'banana',
    'mashed banana':'banana',
    'barbecue sauce':'barbecue sauce',
    'pearl barley':'barley',
    'barley':'barley',
    'sweet basil':'basil',
    'fresh basil':'basil',
    'dried basil':'basil',
    'basil':'basil',
    'fresh basil leaf':'basil',
    'basil leaf':'basil',
    'dried basil leaf':'basil',
    'basmati rice':'basmati rice',
    'bay leaf':'bay leaf',
    'old bay seasoning':'bay leaf',
    'bean':'bean',
    'red bean':'bean',
    'alfalfa sprout':'bean sprout',
    'bean sprout':'bean sprout',
    'ground beef':'beef',
    'lean ground beef':'beef',
    'beef':'beef',
    'ground chuck':'beef',
    'chuck roast':'beef',
    'stewing beef':'beef',
    'corned beef':'beef',
    'beef brisket':'beef brisket',
    'beef broth':'beef broth',
    'beef stock':'beef broth',
    'boneless beef chuck roast':'beef chuck',
    'beef roast':'beef roast',
    'roast beef':'beef roast',
    'beef stew meat':'beef stew meat',
    'beef bouillon':'beef stock',
    'stock':'beef stock',
    'beef consomme':'beef stock',
    'low sodium beef broth':'beef stock',
    'dark beer':'beer',
    'beer':'beer',
    'beet':'beet',
    'red bell pepper':'bell pepper',
    'orange bell pepper':'bell pepper',
    'green bell pepper':'bell pepper',
    'bell pepper':'bell pepper',
    'yellow bell pepper':'bell pepper',
    'berry':'berry',
    'biscuit mix':'biscuit',
    'biscuit':'biscuit',
    'bisquick':'bisquick baking mix',
    'bisquick baking mix':'bisquick baking mix',
    'bittersweet chocolate':'bittersweet chocolate',
    'canned black bean':'black bean',
    'dried black bean':'black bean',
    'black bean':'black bean',
    'black olive':'black olive',
    'pitted black olive':'black olive',
    'black pepper':'black pepper',
    'fresh ground black pepper':'black pepper',
    'salt and black pepper':'black pepper',
    'fresh blackberry':'blackberry',
    'blackberry':'blackberry',
    'blackeyed pea':'blackeyed pea',
    'blue cheese':'blue cheese',
    'blue curacao':'blue curacao',
    'blueberry':'blueberry',
    'fresh blueberry':'blueberry',
    'frozen blueberry':'blueberry',
    'bok choy':'bok choy',
    'pork loin':'boneless pork loin',
    'boneless pork loin':'boneless pork loin',
    'boneless pork loin chop':'boneless pork loin',
    'boneless pork loin roast':'boneless pork loin',
    'boneless skinless chicken breast':'boneless skinless chicken breast',
    'boneless skinless chicken':'boneless skinless chicken breast',
    'skinless chicken breast half':'boneless skinless chicken breast',
    'boneless skinless chicken breast half':'boneless skinless chicken breast',
    'skinless chicken breast':'boneless skinless chicken breast',
    'vegetable bouillon cube':'bouillon cube',
    'bouillon cube':'bouillon cube',
    'chicken bouillon cube':'bouillon cube',
    'beef bouillon cube':'bouillon cube',
    'bourbon':'bourbon whiskey',
    'whiskey':'bourbon whiskey',
    'bow tie pasta':'bow tie pasta',
    'wheat bran':'bran',
    'natural bran':'bran',
    'brandy':'brandy',
    'bratwurst':'bratwurst',
    'bread':'bread',
    'white bread':'bread',
    'french bread':'bread',
    'italian bread':'bread',
    'breadcrumb':'breadcrumb',
    'corn flake crumb':'breadcrumb',
    'dry breadcrumb':'breadcrumb',
    'fine breadcrumb':'breadcrumb',
    'fresh breadcrumb':'breadcrumb',
    'panko breadcrumb':'breadcrumb',
    'italian seasoned breadcrumb':'breadcrumb',
    'plain breadcrumb':'breadcrumb',
    'seasoned bread crumb':'breadcrumb',
    'soft breadcrumb':'breadcrumb',
    'fine dry breadcrumb':'breadcrumb',
    'seasoned dry bread crumb':'breadcrumb',
    'dried breadcrumb':'breadcrumb',
    'breakfast sausage':'breakfast sausage',
    'brie cheese':'brie cheese',
    'fresh broccoli floret':'broccoli',
    'frozen broccoli floret':'broccoli',
    'broccoli':'broccoli',
    'broccoli floret':'broccoli',
    'frozen chopped broccoli':'broccoli',
    'fresh broccoli':'broccoli',
    'frozen broccoli':'broccoli',
    'broth':'broth',
    'spicy brown mustard':'brown mustard',
    'brown rice flour':'brown rice',
    'brown rice':'brown rice',
    'cooked brown rice':'brown rice',
    'brown sugar':'brown sugar',
    'golden brown sugar':'brown sugar',
    'light brown sugar':'brown sugar',
    'splenda brown sugar blend':'brown sugar',
    'soft brown sugar':'brown sugar',
    'dark brown sugar':'brown sugar',
    'raw sugar':'brown sugar',
    'brownie mix':'brownie mix',
    'brussels sprout':'brussels sprout',
    'buckwheat flour':'buckwheat flour',
    'bulgur':'bulgur',
    'butter':'butter',
    'sweet butter':'butter',
    'light butter':'butter',
    'clarified butter':'butter',
    'real butter':'butter',
    'butter bean':'butter bean',
    'buttermilk':'buttermilk',
    'lowfat buttermilk':'buttermilk',
    'butternut squash':'butternut squash',
    'butterscotch chip':'butterscotch pudding',
    'butterscotch schnapps':'butterscotch schnapps',
    'white button mushroom':'button mushroom',
    'button mushroom':'button mushroom',
    'head of cabbage':'cabbage',
    'savoy cabbage':'cabbage',
    'cabbage':'cabbage',
    'green cabbage':'cabbage',
    'red cabbage':'cabbage',
    'caesar salad dressing':'caesar salad dressing',
    'cajun seasoning':'cajun seasoning',
    'cake mix':'cake mix',
    'candy sprinkle':'candy sprinkle',
    'canned tomato':'canned tomato',
    'whole berry cranberry sauce':'canned whole cranberry sauce',
    'cannellini bean':'cannellini bean',
    'canola oil':'canola oil',
    'cantaloupe':'cantaloupe',
    'caper':'caper',
    'red capsicum':'capsicum',
    'caramel sauce':'caramel',
    'caramel':'caramel',
    'caraway seed':'caraway seed',
    'carbonated lemonlime beverage':'carbonated beverage',
    'ground cardamom':'cardamom',
    'cardamom':'cardamom',
    'cardamom pod':'cardamom',
    'carrot':'carrot',
    'baby carrot':'carrot',
    'cashew nut':'cashew',
    'raw cashew':'cashew',
    'cashew':'cashew',
    'caster sugar':'caster sugar',
    'catfish fillet':'catfish',
    'head cauliflower':'cauliflower',
    'cauliflower':'cauliflower',
    'cauliflower floret':'cauliflower',
    'cayenne pepper':'cayenne pepper',
    'cayenne powder':'cayenne pepper',
    'cayenne':'cayenne pepper',
    'ground cayenne pepper':'cayenne pepper',
    'celery':'celery',
    'celery rib':'celery',
    'celery leaf':'celery',
    'celery seed':'celery seed',
    'pork loin chop':'centercut pork loin chop',
    'chambord raspberry liquor':'chambord raspberry liquor',
    'champagne':'champagne',
    'cheddar cheese':'cheddar cheese',
    'sharp cheddar cheese':'cheddar cheese',
    'white cheddar cheese':'cheddar cheese',
    'reducedfat cheddar cheese':'cheddar cheese',
    'cheddar cheese soup':'cheddar cheese',
    'fatfree cheddar cheese':'cheddar cheese',
    'shredded cheddar cheese':'cheddar cheese',
    'lowfat cheddar cheese':'cheddar cheese',
    'extrasharp cheddar cheese':'cheddar cheese',
    'mild cheddar cheese':'cheddar cheese',
    'cheese':'cheese',
    'italian cheese blend':'cheese blend',
    'dried cherry':'cherry',
    'cherry':'cherry',
    'cherry tomato':'cherry tomato',
    'broilerfryer chicken':'chicken',
    'chicken':'chicken',
    'boneless chicken':'chicken',
    'cooked chicken':'chicken',
    'frying chicken':'chicken',
    'whole chicken':'chicken',
    'chicken breast':'chicken breast',
    'chicken breast fillet':'chicken breast',
    'boneless chicken breast half':'chicken breast',
    'boneless chicken breast':'chicken breast',
    'cooked chicken breast':'chicken breast',
    'chicken breast half':'chicken breast',
    'chicken broth':'chicken broth',
    'chicken stock':'chicken broth',
    'chicken bouillon powder':'chicken broth',
    'beef bouillon granule':'chicken broth',
    'fatfree chicken broth':'chicken broth',
    'chicken base':'chicken broth',
    'chicken stock cube':'chicken broth',
    'fat free chicken broth':'chicken broth',
    'reducedsodium chicken broth':'chicken broth',
    'chicken bouillon granule':'chicken broth',
    'chicken bouillon':'chicken broth',
    'reducedsodium fatfree chicken broth':'chicken broth',
    'chicken drumstick':'chicken drumstick',
    'chicken leg':'chicken leg',
    'chicken liver':'chicken liver',
    'chicken piece':'chicken piece',
    'stove top stuffing mix':'chicken stove top stuffing mix',
    'chicken tender':'chicken tender',
    'skinless chicken thigh':'chicken thigh',
    'chicken thigh':'chicken thigh',
    'boneless skinless chicken thigh':'chicken thigh',
    'chicken wing':'chicken wing',
    'canned chickpea':'chickpea',
    'chickpea':'chickpea',
    'low sodium chicken broth':'chiken borth',
    'poblano chile':'chile',
    'dried red chilies':'chile',
    'chipotle chile in adobo':'chile',
    'chili':'chile',
    'red chilies':'chile',
    'red chile':'chile',
    'chilies':'chile',
    'serrano chilies':'chiles',
    'serrano chili':'chiles',
    'chili bean':'chili bean',
    'sambal oelek':'chili paste',
    'chili paste':'chili paste',
    'chili powder':'chili powder',
    'red chili powder':'chili powder',
    'chili sauce':'chili sauce',
    'sweet chili sauce':'chili sauce',
    'chiligarlic sauce':'chiligarlic sauce',
    'chinese five spice powder':'chinese five spice powder',
    'chipotle chile':'chipotle chile',
    'dried chipotle powder':'chipotle chile',
    'chipotle pepper':'chipotle chile',
    'dried chive':'chive',
    'chive':'chive',
    'fresh chive':'chive',
    'chocolate shaving':'chocolate',
    'semisweet chocolate':'chocolate',
    'unsweetened chocolate':'chocolate',
    'milk chocolate':'chocolate',
    'chocolate':'chocolate',
    'semisweet chocolate baking square':'chocolate',
    'semisweet chocolate morsel':'chocolate',
    'unsweetened chocolate square':'chocolate',
    'chocolate cake mix':'chocolate cake mix',
    'mm plain chocolate candy':'chocolate candy',
    'semisweet chocolate chip':'chocolate chip',
    'chocolate chip':'chocolate chip',
    'dark chocolate chip':'chocolate chip',
    'white chocolate chip':'chocolate chip',
    'milk chocolate chip':'chocolate chip',
    'miniature semisweet chocolate chip':'chocolate chip',
    'mini chocolate chip':'chocolate chip',
    'chocolate syrup':'chocolate flavored syrup',
    'chorizo sausage':'chorizo sausage',
    'chow mein noodle':'chow mein noodle',
    'chutney':'chutney',
    'fresh cilantro':'cilantro',
    'cilantro':'cilantro',
    'dried cilantro':'cilantro',
    'fresh cilantro stem':'cilantro',
    'cilantro leaf':'cilantro',
    'fresh cilantro leaf':'cilantro',
    'cinnamon':'cinnamon',
    'ground cinnamon':'cinnamon',
    'cinnamon stick':'cinnamon',
    'cinnamon sugar':'cinnamon',
    'clam':'clam',
    'clam juice':'clam juice',
    'ground clove':'clove',
    'clove':'clove',
    'whole clove':'clove',
    'club soda':'club soda',
    'coarse black pepper':'coarse ground pepper',
    'coarse sea salt':'coarse ground pepper',
    'fresh coarse ground black pepper':'coarse ground pepper',
    'unsweetened cocoa':'cocoa',
    'cocoa':'cocoa powder',
    'dutchprocessed cocoa powder':'cocoa powder',
    'cocoa powder':'cocoa powder',
    'unsweetened cocoa powder':'cocoa powder',
    'sweetened coconut':'coconut',
    'coconut flake':'coconut',
    'coconut':'coconut',
    'shredded coconut':'coconut',
    'desiccated coconut':'coconut',
    'coconut oil':'coconut',
    'unsweetened coconut':'coconut',
    'coconut cream':'coconut',
    'cream of coconut':'coconut cream',
    'coconut extract':'coconut extract',
    'coconut milk':'coconut milk',
    'light coconut milk':'coconut milk',
    'unsweetened coconut milk':'coconut milk',
    'coconut rum':'coconut rum',
    'cod':'cod',
    'cod fish fillet':'cod',
    'coffee liqueur':'coffee',
    'hot coffee':'coffee',
    'coffee':'coffee',
    'brewed coffee':'coffee',
    'strong coffee':'coffee',
    'instant coffee powder':'coffee powder',
    'cognac':'cognac',
    'cointreau liqueur':'cointreau liqueur',
    'colby cheese':'colby cheese',
    'coleslaw mix':'coleslaw',
    'condensed cheddar cheese soup':'condensed cheddar cheese soup',
    'condensed milk':'condensed milk',
    'confectioner sugar':'confectioner sugar',
    'cooked shrimp':'cooked shrimp',
    'cooking oil':'cooking oil',
    'cooking spray':'cooking spray',
    'pam cooking spray':'cooking spray',
    'butterflavored cooking spray':'cooking spray',
    'nonstick cooking spray':'cooking spray',
    'vegetable oil cooking spray':'cooking spray',
    'olive oil flavored cooking spray':'cooking spray',
    'fresh coriander leaf':'coriander',
    'coriander':'coriander',
    'fresh coriander':'coriander',
    'coriander leaf':'coriander',
    'coriander seed':'coriander seed',
    'coriander powder':'coriander seed',
    'corn':'corn',
    'fresh corn':'corn',
    'baby corn':'corn',
    'fresh corn kernel':'corn',
    'frozen whole kernel corn':'corn',
    'corn chip':'corn chip',
    'corn flake':'corn flake',
    'whole kernel corn':'corn kernel',
    'corn kernel':'corn kernel',
    'frozen corn kernel':'corn kernel',
    'corn oil':'corn oil',
    'dark corn syrup':'corn syrup',
    'white corn syrup':'corn syrup',
    'light corn syrup':'corn syrup',
    'corn syrup':'corn syrup',
    'corn tortilla':'corn tortilla chip',
    'tortilla chip':'corn tortilla chip',
    'cornbread':'cornbread',
    'cornmeal':'cornmeal',
    'yellow cornmeal':'cornmeal',
    'cornstarch':'cornstarch',
    'fatfree cottage cheese':'cottage cheese',
    'small curd cottage cheese':'cottage cheese',
    'cottage cheese':'cottage cheese',
    'low fat cottage cheese':'cottage cheese',
    'countrystyle pork rib':'countrystyle boneless pork rib',
    'couscous':'couscous',
    'imitation crabmeat':'crabmeat',
    'crabmeat':'crabmeat',
    'lump crabmeat':'crabmeat',
    'cracked pepper':'cracked pepper',
    'cracked black pepper':'cracked pepper',
    'cracker':'cracker',
    'craisins':'craisins',
    'dried cranberry':'cranberry',
    'dried sweetened cranberry':'cranberry',
    'cranberry juice':'cranberry',
    'cranberry':'cranberry',
    'fresh cranberry':'cranberry',
    'cranberry sauce':'cranberry sauce',
    'cream':'cream',
    'cream cheese':'cream cheese',
    'light cream cheese':'cream cheese',
    'fat free cream cheese':'cream cheese',
    'reducedfat cream cheese':'cream cheese',
    'lowfat cream cheese':'cream cheese',
    'cream of celery soup':'cream of celery soup',
    'cream of chicken soup':'cream of chicken soup',
    'condensed cream of chicken soup':'cream of chicken soup',
    'cream of mushroom soup':'cream of mushroom soup',
    'condensed golden mushroom soup':'cream of mushroom soup',
    'condensed cream of celery soup':'cream of mushroom soup',
    'condensed cream of mushroom soup':'cream of mushroom soup',
    'cream of tartar':'cream of tartar',
    'creamed corn':'creamed corn',
    'creamstyle corn':'creamed corn',
    'creme de cacao':'creme de cacao',
    'creme fraiche':'creme fraiche',
    'creole seasoning':'creole seasoning',
    'crescent roll':'crescent roll',
    'crisco shortening':'crisco allvegetable shortening',
    'crisco':'crisco allvegetable shortening',
    'crispy rice cereal':'crisp rice cereal',
    'crouton':'crouton',
    'crushed pineapple':'crushed pineapple',
    'crusty bread':'crusty bread',
    'cucumber':'cucumber',
    'seedless cucumber':'cucumber',
    'english cucumber':'cucumber',
    'ground cumin':'cumin',
    'cumin':'cumin',
    'cumin seed':'cumin',
    'cumin powder':'cumin',
    'dried currant':'currant',
    'currant':'currant',
    'curry':'curry',
    'curry leaf':'curry leaf',
    'red curry paste':'curry paste',
    'curry paste':'curry paste',
    'curry powder':'curry powder',
    'dark chocolate':'dark chocolate',
    'date':'date',
    'pitted date':'date',
    'deli ham':'deli ham',
    'deli turkey':'deli turkey',
    'devil food cake mix':'devil food cake mix',
    'diced tomato':'diced tomato',
    'chopped tomato':'diced tomato',
    'crushed tomato':'diced tomato',
    'diced tomato with green chilies':'diced tomato',
    'diced tomato with juice':'diced tomato',
    'dijon mustard':'dijon mustard',
    'fresh dill':'dill',
    'dill':'dill',
    'dried dill':'dill',
    'dill pickle':'dill pickle',
    'dill seed':'dill seed',
    'mint sprig':'dill sprig',
    'dill weed':'dill weed',
    'dried dill weed':'dill weed',
    'double cream':'double cream',
    'french dressing':'dressing',
    'thousand island dressing':'dressing',
    'dried apricot':'dried apricot half',
    'dried fruit':'dried fruit',
    'onion flake':'dried onion flake',
    'dried onion flake':'dried onion flake',
    'dried oregano':'dried oregano leaf',
    'dried oregano leaf':'dried oregano leaf',
    'oregano leaf':'dried oregano leaf',
    'dried parsley':'dried parsley flake',
    'parsley flake':'dried parsley flake',
    'dried parsley flake':'dried parsley flake',
    'red chili pepper':'dried red chili pepper',
    'dry mustard':'dry mustard',
    'dry roasted peanut':'dry roasted peanut',
    'roasted peanut':'dry roasted peanut',
    'dry white wine':'dry wine',
    'dry red wine':'dry wine',
    'edamame':'edamame',
    'egg':'egg',
    'egg white':'egg',
    'egg yolk':'egg',
    'hardboiled egg':'egg',
    'extra large egg':'egg',
    'hardcooked egg':'egg',
    'egg noodle':'egg noodle',
    'wide egg noodle':'egg noodle',
    'egg beater egg substitute':'egg substitute',
    'egg substitute':'egg substitute',
    'eggnog':'eggnog',
    'eggplant':'eggplant',
    'elbow macaroni':'elbow macaroni',
    'enchilada sauce':'enchilada sauce',
    'english muffin':'english muffin',
    'espresso':'espresso',
    'instant espresso powder':'espresso',
    'evaporated milk':'evaporated milk',
    'fatfree evaporated milk':'evaporated milk',
    'evaporated skim milk':'evaporated milk',
    'extra lean ground beef':'extra lean ground beef',
    'fat':'fat',
    'fennel':'fennel',
    'fennel bulb':'fennel bulb',
    'fennel seed':'fennel seed',
    'fenugreek seed':'fenugreek leaf',
    'feta cheese':'feta cheese',
    'feta':'feta cheese',
    'fettuccine':'fettuccine',
    'fettuccine pasta':'fettuccine',
    'dried fig':'fig',
    'firm tofu':'firm tofu',
    'extra firm tofu':'firm tofu',
    'fish':'fish',
    'fish fillet':'fish fillet',
    'white fish fillet':'fish fillet',
    'fish sauce':'fish sauce',
    'fish stock':'fish stock',
    'fivespice powder':'fivespice powder',
    'flaked coconut':'flaked coconut',
    'sweetened flaked coconut':'flaked coconut',
    'flank steak':'flank steak',
    'flax seed':'flax seed',
    'ground flax seed':'flax seed',
    'flax seed meal':'flax seed',
    'flour':'flour',
    'plain flour':'flour',
    'bread flour':'flour',
    'self rising flour':'flour',
    'cake flour':'flour',
    'white flour':'flour',
    'unbleached flour':'flour',
    'self raising flour':'flour',
    'selfraising flour':'flour',
    'unbleached white flour':'flour',
    'inch flour tortilla':'flour tortilla',
    'fontina cheese':'fontina',
    'red food coloring':'food coloring',
    'green food coloring':'food coloring',
    'food coloring':'food coloring',
    'frangelico':'frangelico',
    'fresh black pepper':'fresh black pepper',
    'fresh raspberry':'fresh raspberry',
    'frosting':'frosting',
    'frozen corn':'frozen corn',
    'cut green bean':'frozen cut green bean',
    'fresh fruit':'fruit',
    'fruit':'fruit',
    'fruit cocktail':'fruit juice',
    'cranberry juice cocktail':'fruit juice',
    'fusilli':'fusilli',
    'garbanzo bean':'garbanzo bean',
    'garlic granule':'garlic',
    'granulated garlic':'garlic',
    'garlic paste':'garlic',
    'garlic clove':'garlic clove',
    'garlic':'garlic clove',
    'fresh garlic':'garlic clove',
    'minced garlic clove':'garlic clove',
    'fresh garlic clove':'garlic clove',
    'garlic powder':'garlic powder',
    'unflavored gelatin':'gelatin',
    'gelatin':'gelatin',
    'ghee':'ghee',
    'gin':'gin',
    'fresh ginger':'ginger',
    'ground ginger':'ginger',
    'ginger':'ginger',
    'powdered ginger':'ginger',
    'ginger paste':'ginger',
    'candied ginger':'ginger',
    'minced ginger':'ginger',
    'crystallized ginger':'ginger',
    'ginger powder':'ginger',
    'ginger ale':'ginger ale',
    'gingerroot':'gingerroot',
    'fresh gingerroot':'gingerroot',
    'vital wheat gluten':'gluten',
    'cornflour':'glutenfree cornflour',
    'glutenfree flour':'glutenfree flour',
    'goat cheese':'goat cheese',
    'soft fresh goat cheese':'goat cheese',
    'yukon gold potato':'gold leaf foil',
    'golden raisin':'golden seedless raisin',
    'gorgonzola':'gorgonzola',
    'smoked gouda cheese':'gouda',
    'gouda cheese':'gouda cheese',
    'graham cracker crumb':'graham cracker',
    'graham cracker':'graham cracker',
    'graham cracker pie crust':'graham cracker',
    'graham cracker crust':'graham cracker crust',
    'grand marnier':'grand marnier',
    'granola cereal':'granola',
    'granulated sugar':'granulated sugar',
    'splenda granular':'granulated sugar',
    'grape':'grape',
    'grape tomato':'grape tomato',
    'grapefruit':'grapefruit',
    'grapefruit juice':'grapefruit juice',
    'beef gravy':'gravy',
    'brown gravy mix':'gravy',
    'great northern bean':'great northern bean',
    'greek yogurt':'greek yogurt',
    'collard green':'green',
    'green':'green',
    'green bean':'green bean',
    'frozen green bean':'green bean',
    'french style green bean':'green bean',
    'fresh green bean':'green bean',
    'green pepper':'green chili pepper',
    'green chilies':'green chili pepper',
    'diced green chilies':'green chili pepper',
    'green chili pepper':'green chili pepper',
    'chili pepper':'green chili pepper',
    'green chili':'green chili pepper',
    'tomato and green chilies':'green chili pepper',
    'mild green chilies':'green chilies',
    'green onion':'green onion',
    'green onion top':'green onion',
    'frozen pea':'green pea',
    'frozen green pea':'green pea',
    'green pea':'green pea',
    'grenadine':'grenadine',
    'ground coriander':'ground coriander',
    'ground black pepper':'ground pepper',
    'fresh ground pepper':'ground pepper',
    'salt freshly ground black pepper':'ground pepper',
    'ground pepper':'ground pepper',
    'ground red pepper':'ground pepper',
    'kosher salt freshly ground black pepper':'ground pepper',
    'fresh ground white pepper':'ground pepper',
    'lemon pepper':'ground pepper',
    'salt fresh ground pepper':'ground pepper',
    'ground chicken':'ground pepper',
    'ground round':'ground round',
    'ground turkey':'ground turkey',
    'ground turkey breast':'ground turkey',
    'lean ground turkey':'ground turkey',
    'gruyere':'gruyere',
    'gruyere cheese':'gruyere cheese',
    'guacamole':'guacamole',
    'guinness stout':'guinness stout',
    'xanthan gum':'gum paste',
    'habanero pepper':'habanero pepper',
    'fatfree halfandhalf':'halfandhalf',
    'halfandhalf':'halfandhalf cream',
    'halfandhalf cream':'halfandhalf cream',
    'halibut fillet':'halibut',
    'ham':'ham',
    'cooked ham':'ham',
    'smoked ham':'ham',
    'hamburger':'hamburger',
    'hamburger bun':'hamburger bun',
    'bun':'hamburger bun',
    'sandwich bun':'hamburger bun',
    'harissa':'harissa',
    'frozen hash brown potato':'hash brown',
    'frozen hash brown':'hash brown',
    'havarti cheese':'havarti cheese',
    'hazelnut':'hazelnut',
    'heavy cream':'heavy cream',
    'herb':'herb',
    'dried herb':'herb',
    'mixed herb':'herb',
    'fresh herb':'herb',
    'seasoned stuffing mix':'herb seasoned stuffing mix',
    'herbes de provence':'herbs',
    'hoisin sauce':'hoisin sauce',
    'honey':'honey',
    'clear honey':'honey',
    'liquid honey':'honey',
    'honey mustard':'honey mustard',
    'honeydew melon':'honeydew melon',
    'prepared horseradish':'horseradish',
    'horseradish':'horseradish',
    'hot chili sauce':'hot chili bean',
    'hot chili pepper':'hot chili bean',
    'hot dog':'hot dog',
    'hot dog bun':'hot dog bun',
    'hot pepper':'hot pepper',
    'hot pepper sauce':'hot pepper sauce',
    'hot sauce':'hot sauce',
    'frank red hot sauce':'hot sauce',
    'hummus':'hummus',
    'ice':'ice',
    'ice cube':'ice',
    'ice cream':'ice cream',
    'caramel ice cream topping':'ice cream',
    'chocolate ice cream':'ice cream',
    'iceberg lettuce':'iceberg lettuce',
    'icing sugar':'icing',
    'instant coffee':'instant coffee',
    'instant coffee granule':'instant coffee',
    'instant potato flake':'instant potato flake',
    'bailey irish cream':'irish cream',
    'irish cream':'irish cream',
    'irish whiskey':'irish cream',
    'italian breadcrumb':'italian breadcrumb',
    'italian style breadcrumb':'italian breadcrumb',
    'italian salad dressing mix':'italian salad dressing',
    'italian dressing':'italian salad dressing',
    'italian salad dressing':'italian salad dressing',
    'italian sausage':'italian sausage',
    'hot italian sausage':'italian sausage',
    'italian seasoning':'italian seasoning',
    'dried italian seasoning':'italian seasoning',
    'sweet italian sausage':'italian sweet sausage',
    'italianstyle diced tomato':'italianstyle tomato',
    'jalapeno pepper':'jalapeno',
    'jalapeno':'jalapeno',
    'fresh jalapeno':'jalapeno',
    'fresh jalapeno pepper':'jalapeno',
    'jalapeno chile':'jalapeno',
    'jam':'jam',
    'strawberry jam':'jam',
    'jasmine rice':'jasmine rice',
    'jicama':'jicama',
    'juice':'juice',
    'kaffir lime leaf':'kaffir lime leaf',
    'kahlua':'kahlua',
    'kale':'kale',
    'ketchup':'ketchup',
    'catsup':'ketchup',
    'tomato ketchup':'ketchup',
    'key lime juice':'key lime juice',
    'kidney bean':'kidney bean',
    'dark red kidney bean':'kidney bean',
    'red kidney bean':'kidney bean',
    'kielbasa':'kielbasa',
    'kiwi':'kiwi',
    'kiwi fruit':'kiwi',
    'lamb':'lamb',
    'ground lamb':'lamb',
    'lamb shank':'lamb shank',
    'lard':'lard',
    'lasagna noodle':'lasagna noodle',
    'ground lean pork':'lean pork',
    'leek':'leek',
    'leg of lamb':'leg of lamb',
    'lemon':'lemon',
    'lemon wedge':'lemon',
    'lemon slice':'lemon',
    'lemon juice and zest of':'lemon',
    'lemon extract':'lemon extract',
    'lemon juice':'lemon juice',
    'fresh lemon juice':'lemon juice',
    'lemon juice of':'lemon juice',
    'lemon peel':'lemon peel',
    'orange peel':'lemon peel',
    'lemon zest':'lemon rind',
    'orange zest':'lemon rind',
    'lemon zest of':'lemon rind',
    'lemon rind':'lemon rind',
    'lemon rind of':'lemon rind',
    'fresh lemon rind':'lemon rind',
    'fresh lemon zest':'lemon zest',
    'frozen lemonade concentrate':'lemonade',
    'lemonade':'lemonade',
    'lemongrass':'lemongrass',
    'dried lentil':'lentil',
    'brown lentil':'lentil',
    'lentil':'lentil',
    'red lentil':'lentil',
    'lettuce':'lettuce',
    'lettuce leaf':'lettuce',
    'salad green':'lettuce',
    'red leaf lettuce':'lettuce leaf',
    'light cream':'light cream',
    'philadelphia cream cheese':'light cream cheese',
    'lima bean':'lima bean',
    'lime slice':'lime',
    'lime':'lime',
    'lime wedge':'lime',
    'lime peel':'lime',
    'lime juice':'lime juice',
    'fresh lime juice':'lime juice',
    'lime juice of':'lime juice',
    'lime zest':'lime rind',
    'lime juice and zest of':'lime zest',
    'lime zest of':'lime zest',
    'lime rind':'lime zest',
    'frozen limeade concentrate':'limeade',
    'linguine':'linguine',
    'liquid smoke':'liquid smoke',
    'long grain rice':'long grain rice',
    'long grain white rice':'long grain rice',
    'long grain and wild rice blend':'long grain rice',
    'longgrain rice':'long grain rice',
    'longgrain white rice':'long grain rice',
    'cooked longgrain rice':'longgrain rice',
    'lowfat milk':'lowfat milk',
    'lowfat vanilla yogurt':'lowfat yogurt',
    'lowfat yogurt':'lowfat yogurt',
    'macadamia nut':'macadamia nut',
    'macaroni':'macaroni',
    'mace':'mace',
    'ground mace':'mace',
    'malt vinegar':'malt vinegar',
    'mandarin orange':'mandarin orange',
    'mandarin orange segment':'mandarin orange',
    'mango':'mango',
    'mango chutney':'mango chutney',
    'manicotti':'manicotti',
    'maple extract':'maple extract',
    'maple syrup':'maple syrup',
    'pure maple syrup':'maple syrup',
    'maraschino cherry':'maraschino cherry',
    'margarine':'margarine',
    'marinara sauce':'marinara sauce',
    'marjoram':'marjoram',
    'fresh marjoram':'marjoram',
    'dried marjoram':'marjoram',
    'orange marmalade':'marmalade',
    'marsala wine':'marsala wine',
    'miniature marshmallow':'marshmallow',
    'marshmallow':'marshmallow',
    'mini marshmallow':'marshmallow',
    'marshmallow cream':'marshmallow cream',
    'marshmallow creme':'marshmallow creme',
    'garam masala':'masala',
    'mascarpone cheese':'mascarpone cheese',
    'mashed potato':'mashed potato',
    'matzo meal':'matzo meal',
    'mayonnaise':'mayonnaise',
    'light mayonnaise':'mayonnaise',
    'hellmanns mayonnaise':'mayonnaise',
    'reducedfat mayonnaise':'mayonnaise',
    'lowfat mayonnaise':'mayonnaise',
    'fatfree mayonnaise':'mayonnaise',
    'meat':'meat',
    'meatball':'meatball',
    'mexican blend cheese':'mexican cheese blend',
    'midori melon liqueur':'midori melon liqueur',
    'milk':'milk',
    'skim milk':'milk',
    'whole milk':'milk',
    'dry milk':'milk powder',
    'nonfat dry milk powder':'milk powder',
    'of fresh mint':'mint',
    'fresh mint leaf':'mint',
    'mint leaf':'mint',
    'mint':'mint',
    'dried mint':'mint',
    'miracle whip':'miracle whip',
    'mirin':'mirin',
    'mixed green':'mixed green',
    'mixed salad green':'mixed green',
    'frozen mixed vegetable':'mixed vegetable',
    'mixed vegetable':'mixed vegetable',
    'molasses':'molasses',
    'dark molasses':'molasses',
    'monterey jack cheese':'monterey jack cheese',
    'monterey jack pepper cheese':'monterey jack cheese',
    'colbymonterey jack cheese':'monterey jack cheese',
    'mozzarella cheese':'mozzarella cheese',
    'partskim mozzarella cheese':'mozzarella cheese',
    'fresh mozzarella cheese':'mozzarella cheese',
    'msg':'msg',
    'muenster cheese':'muenster cheese',
    'mushroom':'mushroom',
    'fresh mushroom':'mushroom',
    'sliced mushroom':'mushroom',
    'mixed mushroom':'mushroom',
    'mushroom stem and piece':'mushroom',
    'white mushroom':'mushroom',
    'cremini mushroom':'mushroom',
    'mushroom soup':'mushroom soup',
    'mussel':'mussel',
    'coarse grain mustard':'mustard',
    'mustard':'mustard',
    'yellow mustard':'mustard',
    'grainy mustard':'mustard',
    'ground mustard':'mustard',
    'dijonstyle mustard':'mustard',
    'mustard powder':'mustard powder',
    'mustard seed':'mustard seed',
    'black mustard seed':'mustard seed',
    'napa cabbage':'napa cabbage leaf',
    'naturalstyle peanut butter':'naturalstyle chunky peanut butter',
    'navy bean':'navy bean',
    'nectarine':'nectarine',
    'neufchatel cheese':'neufchatel cheese',
    'nonfat milk':'nonfat milk',
    'nonfat plain yogurt':'nonfat yogurt',
    'nonfat yogurt':'nonfat yogurt',
    'nonfat vanilla yogurt':'nonfat yogurt',
    'plain nonfat yogurt':'nonfat yogurt',
    'noodle':'noodle',
    'nut':'nut',
    'mixed nut':'nut',
    'nutella':'nutella',
    'nutmeg':'nutmeg',
    'ground nutmeg':'nutmeg',
    'rolled oat':'oat',
    'oatmeal':'oat',
    'oat':'oat',
    'quickcooking oat':'oat',
    'old fashioned oat':'oat',
    'quick oat':'oat',
    'quickcooking rolled oat':'oat',
    'oat bran':'oat',
    'quickcooking oatmeal':'oatmeal',
    'oil':'oil',
    'salad oil':'oil',
    'grapeseed oil':'oil',
    'chili oil':'oil',
    'safflower oil':'oil',
    'okra':'okra',
    'kalamata olive':'olive',
    'olive':'olive',
    'green olive':'olive',
    'pimento stuffed olive':'olive',
    'sliced ripe olive':'olive',
    'olive oil':'olive oil',
    'extra virgin olive oil':'olive oil',
    'virgin olive oil':'olive oil',
    'light olive oil':'olive oil',
    'onion':'onion',
    'brown onion':'onion',
    'white onion':'onion',
    'diced onion':'onion',
    'vidalia onion':'onion',
    'instant minced onion':'onion',
    'white pearl onion':'onion',
    'frenchfried onion':'onion',
    'dried onion':'onion',
    'onion powder':'onion powder',
    'lipton onion soup mix':'onion soup',
    'onion soup mix':'onion soup mix',
    'dry onion soup mix':'onion soup mix',
    'orange slice':'orange',
    'orange':'orange',
    'navel orange':'orange',
    'orange extract':'orange extract',
    'orange juice':'orange juice',
    'orange juice concentrate':'orange juice',
    'fresh orange juice':'orange juice',
    'frozen orange juice concentrate':'orange juice',
    'orange juice of':'orange juice',
    'orange liqueur':'orange liqueur',
    'orange rind':'orange rind',
    'orange zest of':'orange rind',
    'oregano':'oregano',
    'fresh oregano':'oregano',
    'ground oregano':'oregano',
    'mexican oregano':'oregano',
    'oreo cooky':'oreo cooky',
    'a original sauce':'original sauce',
    'orzo pasta':'orzo pasta',
    'oyster':'oyster',
    'oyster sauce':'oyster sauce',
    'palm sugar':'palm sugar',
    'pancetta':'pancetta',
    'papaya':'papaya',
    'paprika':'paprika',
    'sweet paprika':'paprika',
    'smoked paprika':'paprika',
    'hungarian paprika':'paprika',
    'parmesan cheese':'parmesan cheese',
    'fresh parmesan cheese':'parmesan cheese',
    'parmigianoreggiano cheese':'parmigianoreggiano cheese',
    'fresh parsley':'parsley',
    'parsley':'parsley',
    'flat leaf parsley':'parsley',
    'parsley sprig':'parsley',
    'fresh parsley leaf':'parsley',
    'fresh flatleaf parsley':'parsley',
    'flatleaf italian parsley':'parsley',
    'italian parsley':'parsley',
    'fresh italian parsley':'parsley',
    'parsnip':'parsnip',
    'pasta':'pasta',
    'cooked pasta':'pasta',
    'farfalle pasta':'pasta',
    'rigatoni pasta':'pasta',
    'pasta sauce':'pasta sauce',
    'small shell pasta':'pasta shell',
    'pasta shell':'pasta shell',
    'jumbo pasta shell':'pasta shell',
    'pea':'pea',
    'split pea':'pea',
    'peach':'peach',
    'fresh peach':'peach',
    'peanut':'peanut',
    'salted peanut':'peanut',
    'unsalted peanut':'peanut',
    'peanut butter':'peanut butter',
    'creamy peanut butter':'peanut butter',
    'peanut butter chip':'peanut butter',
    'smooth peanut butter':'peanut butter',
    'crunchy peanut butter':'peanut butter',
    'chunky peanut butter':'peanut butter',
    'peanut oil':'peanut oil',
    'pear':'pear',
    'frozen baby pea':'peas',
    'frozen pea and carrot':'peas',
    'pecan':'pecan',
    'pecan half':'pecan',
    'pecan piece':'pecan',
    'pecorino romano cheese':'pecorino cheese',
    'penne pasta':'penne',
    'penne':'penne',
    'pepper':'pepper',
    'white pepper':'pepper',
    'poblano pepper':'pepper',
    'pepperoncini pepper':'pepper',
    'lemon pepper seasoning':'pepper',
    'black peppercorn':'peppercorn',
    'peppercorn':'peppercorn',
    'whole black peppercorn':'peppercorn',
    'peppermint extract':'peppermint',
    'pepperoni':'pepperoni',
    'pesto sauce':'pesto sauce',
    'basil pesto':'pesto sauce',
    'phyllo pastry':'phyllo pastry sheet',
    'phyllo dough':'phyllo pastry sheet',
    'picante sauce':'picante sauce',
    'pickle':'pickle',
    'pickle juice':'pickle',
    'sweet pickle relish':'pickle',
    'pickled jalapeno pepper':'pickled jalapeno pepper',
    'pie crust':'pie crust',
    'refrigerated pie crust':'pie crust',
    'cherry pie filling':'pie filling',
    'apple pie filling':'pie filling',
    'inch pie shell':'pie shell',
    'deep dish pie shell':'pie shell',
    'unbaked pie shell':'pie shell',
    'pie shell':'pie shell',
    'refrigerated crescent dinner roll':'pillsbury refrigerated crescent dinner roll',
    'pillsbury refrigerated crescent dinner roll':'pillsbury refrigerated crescent dinner roll',
    'diced pimento':'pimento',
    'pimiento':'pimiento',
    'chopped pimiento':'pimiento',
    'pine nut':'pine nut',
    'crushed pineapple in juice':'pineapple',
    'pineapple':'pineapple',
    'pineapple chunk':'pineapple',
    'pineapple chunk in juice':'pineapple',
    'fresh pineapple':'pineapple',
    'pineapple tidbit':'pineapple',
    'pineapple slice':'pineapple',
    'pineapple juice':'pineapple juice',
    'unsweetened pineapple juice':'pineapple juice',
    'pinto bean':'pinto bean',
    'pistachio nut':'pistachio',
    'pistachio':'pistachio',
    'pita bread':'pita bread',
    'prepared pizza crust':'pizza crust',
    'pizza crust':'pizza crust',
    'pizza dough':'pizza dough',
    'pizza sauce':'pizza sauce',
    'plain yogurt':'plain yogurt',
    'plain lowfat yogurt':'plain yogurt',
    'plain fatfree yogurt':'plain yogurt',
    'lowfat plain yogurt':'plain yogurt',
    'plantain':'plantain',
    'plum':'plum',
    'plum tomato':'plum tomato',
    'polenta':'polenta',
    'pomegranate juice':'pomegranate juice',
    'popped popcorn':'popped popcorn',
    'poppy seed':'poppy seed',
    'ground pork':'pork',
    'pork':'pork',
    'pork and bean':'pork',
    'pork chop':'pork chop',
    'boneless pork chop':'pork chop',
    'pork sausage':'pork sausage',
    'pork shoulder':'pork shoulder',
    'boneless pork shoulder':'pork shoulder',
    'pork tenderloin':'pork tenderloin steak',
    'port wine':'port wine',
    'portabella mushroom':'portabella mushroom',
    'portabella mushroom cap':'portabella mushroom',
    'baby portabella mushroom':'portabella mushroom',
    'potato':'potato',
    'red potato':'potato',
    'russet potato':'potato',
    'idaho potato':'potato',
    'new potato':'potato',
    'boiling potato':'potato',
    'small red potato':'potato',
    'white potato':'potato',
    'potato chip':'potato chip',
    'powdered milk':'powdered milk',
    'powdered sugar':'powdered sugar',
    'prawn':'prawn',
    'prepared mustard':'prepared mustard',
    'prepared yellow mustard':'prepared mustard',
    'apricot preserve':'preserve',
    'raspberry preserve':'preserve',
    'pretzel':'pretzel',
    'pretzel stick':'pretzel',
    'prosciutto':'prosciutto',
    'provolone cheese':'provolone cheese',
    'prune':'prune',
    'puff pastry':'puff pastry',
    'frozen puff pastry':'puff pastry',
    'puff pastry sheet':'puff pastry sheet',
    'pumpkin':'pumpkin',
    'pumpkin puree':'pumpkin',
    'canned pumpkin':'pumpkin',
    'pumpkin pie spice':'pumpkin pie spice',
    'pumpkin seed':'pumpkin seed',
    'queso fresco':'queso fresco',
    'queso fresco':'queso fresco',
    'quinoa':'quinoa',
    'radish':'radish',
    'raisin':'raisin',
    'seedless raisin':'raisin',
    'dark raisin':'raisin',
    'sultana':'raisin',
    'ramen noodle':'ramen noodle',
    'ranch dressing':'ranch dressing',
    'dry ranch dressing mix':'ranch dressing',
    'ranch dressing mix':'ranch dressing',
    'ranch salad dressing':'ranch salad dressing',
    'raspberry':'raspberry',
    'frozen raspberry':'raspberry',
    'raspberry jam':'raspberry jam',
    'crushed red pepper flake':'red chili pepper flake',
    'red pepper flake':'red chili pepper flake',
    'dried chili pepper flake':'red chili pepper flake',
    'red chili pepper flake':'red chili pepper flake',
    'hot pepper flake':'red chili pepper flake',
    'hot red pepper flake':'red chili pepper flake',
    'dried red pepper flake':'red chili pepper flake',
    'chili flake':'red chili pepper flake',
    'louisiana hot sauce':'red hot sauce',
    'red onion':'red onion',
    'purple onion':'red onion',
    'spanish onion':'red onion',
    'red pepper':'red pepper',
    'dry crushed red pepper':'red pepper',
    'red snapper fillet':'red snapper',
    'red wine':'red wine',
    'refried bean':'refried bean',
    'refrigerated biscuit':'refrigerated biscuit',
    'refrigerated buttermilk biscuit':'refrigerated biscuit',
    'rhubarb':'rhubarb',
    'cooked rice':'rice',
    'rice':'rice',
    'white rice':'rice',
    'minute rice':'rice',
    'uncooked rice':'rice',
    'cooked white rice':'rice',
    'instant rice':'rice',
    'rice flour':'rice flour',
    'rice krispies':'rice krispies',
    'rice noodle':'rice noodle',
    'vermicelli':'rice vermicelli',
    'rice vinegar':'rice vinegar',
    'rice wine vinegar':'rice vinegar',
    'rice wine':'rice wine',
    'ricotta cheese':'ricotta cheese',
    'lowfat ricotta cheese':'ricotta cheese',
    'partskim ricotta cheese':'ricotta cheese',
    'ripe olive':'ripe olive',
    'pitted ripe olive':'ripe olive',
    'ritz cracker':'ritz cracker',
    'cracker crumb':'ritz cracker crumb',
    'pork roast':'roast pork',
    'roasted garlic':'roasted garlic',
    'roasted red pepper':'roasted red pepper',
    'roasting chicken':'roasting chicken',
    'hoagie roll':'roll',
    'kaiser roll':'roll',
    'roll':'roll',
    'romaine lettuce':'romaine lettuce',
    'romaine lettuce leaf':'romaine lettuce',
    'romano cheese':'romano cheese',
    'fresh rosemary':'rosemary',
    'rosemary':'rosemary',
    'dried rosemary':'rosemary',
    'rosemary sprig':'rosemary',
    'fresh rosemary leaf':'rosemary',
    'rotel':'rotel tomato',
    'rotel tomato chilies':'rotel tomato',
    'rotini pasta':'rotini pasta',
    'round steak':'round steak',
    'rum':'rum',
    'dark rum':'rum',
    'white rum':'rum',
    'light rum':'rum',
    'rum extract':'rum extract',
    'rutabaga':'rutabaga',
    'rye bread':'rye bread',
    'rye flour':'rye flour',
    'saffron':'saffron',
    'saffron thread':'saffron',
    'rubbed sage':'sage',
    'sage':'sage',
    'fresh sage':'sage',
    'dried sage':'sage',
    'sage leaf':'sage',
    'fresh sage leaf':'sage',
    'ground sage':'sage',
    'sake':'sake',
    'salad dressing':'salad dressing',
    'salami':'salami',
    'salmon fillet':'salmon',
    'salmon':'salmon',
    'salmon steak':'salmon',
    'salsa':'salsa',
    'salsa verde':'salsa',
    'chunky salsa':'salsa',
    'salt':'salt',
    'salt and pepper':'salt',
    'kosher salt':'salt',
    'sea salt':'salt',
    'garlic salt':'salt',
    'seasoning salt':'salt',
    'salt pepper':'salt',
    'coarse salt':'salt',
    'fine sea salt':'salt',
    'celery salt':'salt',
    'season salt':'salt',
    'table salt':'salt',
    'onion salt':'salt',
    'pickling salt':'salt',
    'lawrys seasoned salt':'salt',
    'salted butter':'salted butter',
    'saltine cracker':'saltine cracker',
    'sauerkraut':'sauerkraut',
    'bulk pork sausage':'sausage',
    'sausage':'sausage',
    'scallion':'scallion',
    'bay scallop':'scallop',
    'sea scallop':'scallop',
    'scallop':'scallop',
    'peach schnapps':'schnapps',
    'scotch bonnet pepper':'scotch bonnet pepper',
    'seasoning':'seasoning',
    'accent seasoning':'seasoning',
    'chili seasoning mix':'seasoning',
    'lemonpepper seasoning':'seasoning',
    'garlic pepper seasoning':'seasoning',
    'mixed spice':'seasoning',
    'italian spice':'seasoning',
    'spice':'seasoning',
    'mccormick montreal brand steak seasoning':'seasoning mix',
    'mr dash seasoning mix':'seasoning mix',
    'red seedless grape':'seedless grape',
    'seedless grape':'seedless grape',
    'green seedless grape':'seedless grape',
    'selfrising flour':'selfrising flour',
    'serrano pepper':'serrano pepper',
    'sesame oil':'sesame oil',
    'dark sesame oil':'sesame oil',
    'toasted sesame oil':'sesame oil',
    'sesame seed':'sesame seed',
    'toasted sesame seed':'sesame seed',
    'shallot':'shallot',
    'dry sherry':'sherry wine',
    'sherry wine':'sherry wine',
    'sherry wine vinegar':'sherry wine vinegar',
    'shiitake mushroom':'shiitake mushroom',
    'shortening':'shortening',
    'vegetable shortening':'shortening',
    'shrimp':'shrimp',
    'large shrimp':'shrimp',
    'medium shrimp':'shrimp',
    'raw shrimp':'shrimp',
    'baby shrimp':'shrimp',
    'jumbo shrimp':'shrimp',
    'small shrimp':'shrimp',
    'ground sirloin':'sirloin',
    'sirloin steak':'sirloin',
    'wooden skewer':'skewer',
    'skewer':'skewer',
    'bamboo skewer':'skewer',
    'smoked salmon':'smoked salmon',
    'smoked sausage':'smoked sausage',
    'smoked bacon':'smoked streaky bacon',
    'snow pea':'snow pea',
    'sour cream':'sour cream',
    'light sour cream':'sour cream',
    'lowfat sour cream':'sour cream',
    'nonfat sour cream':'sour cream',
    'fat free sour cream':'sour cream',
    'reducedfat sour cream':'sour cream',
    'sourdough starter':'sourdough',
    'sourdough bread':'sourdough bread',
    'soy sauce':'soy sauce',
    'low sodium soy sauce':'soy sauce',
    'light soy sauce':'soy sauce',
    'reduced sodium soy sauce':'soy sauce',
    'soya sauce':'soy sauce',
    'dark soy sauce':'soy sauce',
    'tamari soy sauce':'soy sauce',
    'soymilk':'soymilk',
    'spaghetti':'spaghetti',
    'thin spaghetti':'spaghetti',
    'spaghetti noodle':'spaghetti',
    'spaghetti sauce':'spaghetti sauce',
    'spaghetti squash':'spaghetti squash',
    'pork sparerib':'sparerib',
    'sparkling water':'sparkling water',
    'spinach':'spinach',
    'fresh spinach':'spinach',
    'frozen chopped spinach':'spinach',
    'baby spinach':'spinach',
    'frozen spinach':'spinach',
    'baby spinach leaf':'spinach',
    'spinach leaf':'spinach',
    'fresh spinach leaf':'spinach',
    'spring onion':'spring onion',
    'sprite':'sprite',
    'squash':'squash',
    'sriracha sauce':'sriracha sauce',
    'star anise':'star anise',
    'potato starch':'starch',
    'steak':'steak',
    'rib eye steak':'steak',
    'skirt steak':'steak',
    'cube steak':'steak',
    'steak sauce':'steak sauce',
    'stew meat':'stew meat',
    'stewed tomato':'stewed tomato',
    'strawberry':'strawberry',
    'fresh strawberry':'strawberry',
    'frozen strawberry':'strawberry',
    'strawberry jello gelatin dessert':'strawberry gelatin',
    'strawberry gelatin':'strawberry gelatin',
    'sugar':'sugar',
    'white sugar':'sugar',
    'superfine sugar':'sugar',
    'turbinado sugar':'sugar',
    'vanilla sugar':'sugar',
    'sugar snap pea':'sugar snap pea',
    'splenda sugar substitute':'sugar substitute',
    'sugar substitute':'sugar substitute',
    'instant chocolate pudding mix':'sugarfree instant chocolate pudding mix',
    'summer squash':'summer squash',
    'sundried tomato':'sundried tomato',
    'sundried tomato packed in oil':'sundried tomato',
    'sunflower oil':'sunflower oil',
    'sunflower seed':'sunflower seed',
    'sweet corn':'sweet corn',
    'sweet onion':'sweet onion',
    'sweet pepper':'sweet pepper',
    'sweet green pepper':'sweet pepper',
    'sweet potato':'sweet potato',
    'sweet red pepper':'sweet red pepper',
    'sweetened condensed milk':'sweetened condensed milk',
    'artificial sweetener':'sweetener',
    'swiss chard':'swiss chard',
    'swiss cheese':'swiss cheese',
    'golden syrup':'syrup',
    'simple syrup':'syrup',
    'syrup':'syrup',
    'tabasco sauce':'tabasco sauce',
    'taco sauce':'taco sauce',
    'taco seasoning':'taco seasoning',
    'taco seasoning mix':'taco seasoning',
    'taco shell':'taco shell',
    'tahini':'tahini',
    'tamari':'tamari',
    'tamarind paste':'tamarind paste',
    'quickcooking tapioca':'tapioca',
    'tapioca flour':'tapioca flour',
    'dried tarragon':'tarragon',
    'fresh tarragon':'tarragon',
    'tarragon':'tarragon',
    'tarragon vinegar':'tarragon vinegar',
    'tart apple':'tart apple',
    'tasty cheese':'tasty cheese',
    'tea':'tea',
    'tea bag':'tea bag',
    'beef tenderloin':'tenderloin',
    'tequila':'tequila',
    'teriyaki sauce':'teriyaki sauce',
    'dried thyme':'thyme',
    'thyme':'thyme',
    'fresh thyme':'thyme',
    'fresh thyme leave':'thyme',
    'fresh thyme sprig':'thyme',
    'ground thyme':'thyme',
    'dried thyme leaf':'thyme leaf',
    'thyme leaf':'thyme leaf',
    'fresh thyme leaf':'thyme leaf',
    'tilapia fillet':'tilapia fillet',
    'cheerio toasted oat cereal':'toasted oat cereal',
    'toffee piece':'toffee',
    'silken tofu':'tofu',
    'tofu':'tofu',
    'tomatillo':'tomatillo',
    'tomato':'tomato',
    'whole canned tomato':'tomato',
    'rom tomato':'tomato',
    'fresh tomato':'tomato',
    'green tomato':'tomato',
    'tomato with juice':'tomato',
    'tomato soup':'tomato',
    'whole tomato':'tomato',
    'italian plum tomato':'tomato',
    'rotel tomato':'tomato',
    'italian tomato':'tomato',
    'tomato juice':'tomato juice',
    'tomato paste':'tomato paste',
    'tomato puree':'tomato puree',
    'tomato sauce':'tomato sauce',
    'condensed tomato soup':'tomato soup',
    'toothpick':'toothpick',
    'cheese tortellini':'tortellini',
    'tortilla':'tortilla',
    'flour tortilla':'tortilla flour',
    'triple sec':'triple sec',
    'tuna':'tuna',
    'tuna in water':'tuna',
    'tuna steak':'tuna',
    'cooked turkey':'turkey',
    'turkey':'turkey',
    'turkey breast':'turkey',
    'turkey bacon':'turkey bacon',
    'turmeric':'turmeric powder',
    'ground turmeric':'turmeric powder',
    'turmeric powder':'turmeric powder',
    'turnip':'turnip',
    'unsalted butter':'unsalted butter',
    'vanilla':'vanilla',
    'vanilla extract':'vanilla',
    'pure vanilla extract':'vanilla',
    'vanilla essence':'vanilla',
    'vanilla bean':'vanilla',
    'vanilla ice cream':'vanilla ice cream',
    'instant vanilla pudding':'vanilla instant pudding mix',
    'vanilla instant pudding mix':'vanilla instant pudding mix',
    'vanilla pudding mix':'vanilla pudding mix',
    'vanilla wafer':'vanilla wafer',
    'ground veal':'veal',
    'vegetable':'vegetable',
    'vegetable broth':'vegetable broth',
    'vegetable stock':'vegetable broth',
    'vegetable oil':'vegetable oil',
    'poultry seasoning':'vegetarian poultry seasoning',
    'velveeta cheese':'velveeta cheese',
    'dry vermouth':'vermouth',
    'balsamic vinaigrette':'vinaigrette dressing',
    'vinegar':'vinegar',
    'white vinegar':'vinegar',
    'distilled white vinegar':'vinegar',
    'raspberry vinegar':'vinegar',
    'seasoned rice vinegar':'vinegar',
    'vodka':'vodka',
    'vanilla vodka':'vodka',
    'walnut':'walnut',
    'walnut piece':'walnut',
    'walnut half':'walnut',
    'walnut oil':'walnut oil',
    'water':'water',
    'boiling water':'water',
    'cold water':'water',
    'warm water':'water',
    'hot water':'water',
    'ice water':'water',
    'water chestnut':'water chestnut',
    'sliced water chestnut':'water chestnut',
    'watercress':'watercress',
    'watermelon':'watermelon',
    'wheat flour':'wheat flour',
    'wheat germ':'wheat germ',
    'cool whip topping':'whipped cream',
    'cool whip lite':'whipped cream',
    'whipped cream':'whipped cream',
    'cool whip':'whipped cream',
    'whipped topping':'whipped cream',
    'frozen whipped topping':'whipped cream',
    'sweetened whipped cream':'whipped cream',
    'whipping cream':'whipping cream',
    'heavy whipping cream':'whipping cream',
    'white bean':'white bean',
    'white cake mix':'white cake mix',
    'white chocolate':'white chocolate',
    'white bread flour':'white flour',
    'white wine':'white wine',
    'white wine vinegar':'white wine vinegar',
    'whole grain mustard':'whole grain bread',
    'whole wheat bread':'whole wheat bread',
    'whole wheat flour':'whole wheat flour',
    'whole wheat pastry flour':'whole wheat flour',
    'whole wheat tortilla':'whole wheat tortilla',
    'wild rice':'wild rice',
    'wine':'wine',
    'burgundy wine':'wine',
    'madeira wine':'wine',
    'red wine vinegar':'wine vinegar',
    'wine vinegar':'wine vinegar',
    'wonton wrapper':'wonton wrapper',
    'worcestershire sauce':'worcestershire sauce',
    'egg roll wrap':'wrap',
    'yam':'yam',
    'bread machine yeast':'yeast',
    'yeast':'yeast',
    'dry yeast':'yeast',
    'instant yeast':'yeast',
    'nutritional yeast':'yeast',
    'fast rising yeast':'yeast',
    'yellow cake mix':'yellow cake mix',
    'yellow food coloring':'yellow food coloring paste',
    'yellow onion':'yellow onion',
    'yellow pepper':'yellow pepper',
    'yellow squash':'yellow squash',
    'yoghurt':'yoghurt',
    'yogurt':'yogurt',
    'vanilla yogurt':'yogurt',
    'ziti pasta':'ziti pasta',
    'zucchini':'zucchini',
    'courgette':'zucchini'}
